dist: xenial

language: minimal

env:
  global:
    - REPO=docksal/nginx

  matrix:
    - VERSION=1.15 TAGS=latest
    - VERSION=1.14
    - VERSION=1.13
    - VERSION=1.12

install:
  - curl -fsSL get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"

after_failure:
  - make logs
